### PR TITLE
Feature/webextension

### PR DESCRIPTION
**Pull request by FelisCatus**
This PR attempts to port SwitchyOmega to Firefox where WebExtension is supported.

It does not use the full `browser.*` namespace yet. Many `chrome.*` APIs are still used. Therefore, it is unlikely to run under a pure WebExtension environment without the `chrome.*` shim.

All features should be working including proxy switching and everything else. If not, please open an issue.

Also, Options Synchronization does not fully work because `webextensions.browser.storage.sync` is disabled by default in flags. I haven't tested with that flag enabled yet.

To test, please build the project under branch `feature/webextension`. Then use Firefox's Debugging Tools to `Load Temporary Add-on` with `omega-target-chromium-extension/build/manifest.json`.

### CODE REVIEW

**Comment by FelisCatus** [comment]
Need someone to test this on Firefox Nightly now.

**Comment by FelisCatus** [comment]
Submittted to [Mozilla Add-ons](https://addons.mozilla.org/en-US/firefox/addon/switchyomega/). Pending review now.

**Comment by yfdyh000** [comment]
`Error: Unparseable host permission  ExtensionsUI.jsm:250:15` when try installing the `proxy_switchyomega-2.4.8-an+fx.xpi` from Add-ons Manager - Tools menu on Nightly 55.0a1 (2017-04-14) (32-bit). works for load it from `about:debugging#addons`.

Removed the `"ftp://*/*",` from `manifest.json` will fix this issue.
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/permissions
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Match_patterns#scheme no the `ftp` support.

**Comment by yfdyh000** [comment]
Firefox require the https://developer.chrome.com/extensions/optionsV2.
https://developer.chrome.com/extensions/optionsV2
https://bugzilla.mozilla.org/show_bug.cgi?id=1212684

**Comment by FelisCatus** [comment]
It clearly says `ftp` in one of the supported schemes and there is even an example entry there.
But anyway, I think I can use `<all_urls>` for this. It was disabled due to a Chrome issue (See #21), but I don't think the same thing will happen on Firefox.

I will look into options v2. For now, please just use the debug loading method for further testing.

**Comment by FelisCatus** [comment]
All right. Here you go.
This should fix the ftp issues and it uses options_ui for options page.

Please note that the `.xpi` is gone since Mozilla disabled the extension due to not passing the review. However, you can still do `grunt release` in `omega-target-chromium-extension` to generate `build.zip`, which is the same as the XPI with regards to manifest checking. This time all checks should pass.

**Comment by tansinan** [comment]
It works! But why I'm asked to choose the version for angular upon "npm run deps"?

**Comment by FelisCatus** [comment]
I've marked `1.5.11` as a resolution in `bower.json`. It shouldn't require manual selection now.

**Comment by tansinan** [comment]
With webextensions.storage.sync.enabled set to true, synchronization works.

**Comment by yfdyh000** [comment]
FYI: https://bugzilla.mozilla.org/show_bug.cgi?id=1371879

**Comment by FelisCatus** [comment]
@yfdyh000 Changed to new API. Thanks for the link.

**Pull request merged**
