### PR TITLE
literal IPv6 address in a URL should be enclosed

### PR DESCRIPTION
**Pull request by l2dy**
in "[" and "]" characters

### CODE REVIEW

**Comment by FelisCatus** [comment]
In PAC scripts, the IPv6 address will be passed as unenclosed in the `host` parameter. Here's the PAC script I used to verify this:

```js
function FindProxyForURL(url, host) {
  alert(host);
  alert(url);
  return "DIRECT";
}
```

If you load the PAC script in Chrome and open `chrome://net-internals/#events`, you can see the JavaScript alerts there. It should show `::1` for `host` when visiting `http://[::1]/`,

Please let me know if you have different observations.

**Comment by FelisCatus** [comment]
I would also like to add that the SwitchyOmega request parser also generates `::1` when parsing the URL `http://[::1]/` so the icon display and so on should also work with `::1`. https://github.com/l2dy/SwitchyOmega/blob/master/omega-pac/src/conditions.coffee#L13

**Comment by l2dy** [comment]
My observation is that `::1` in the default Bypass List doesn't work while `[::1]` does. I'm not familiar with this project and might have touched irrelevant lines.

**Comment by FelisCatus** [comment]
@l2dy Thanks for the report! Created #998 for this.

It seems that this only applies to Chromium when a proxy profile is applied as-is without any PAC generation. This needs to be separately handled. I shall propose a fix soon.

**Pull request closed without merging**
