### PR TITLE
WebExtension Proxy Script Fixes

### PR DESCRIPTION
**Pull request by FelisCatus**
* Fix potential race condition for proxyScriptLoaded event.
* Try sending messages 10 times! :wink:

You can try a pre-built, unsigned version against the tip of the branch. Make sure to rename it to `.xpi` after you download and then install the extension. NOTE: You will also need to [disable signing requirement](https://wiki.mozilla.org/Add-ons/Extension_Signing#FAQ), by changing `xpinstall.signatures.required` to `false` in `about:config`.

[proxy_switchyomega-2.5.1_4598afb8.zip](https://github.com/FelisCatus/SwitchyOmega/files/1206617/proxy_switchyomega-2.5.1_4598afb8.zip)

### CODE REVIEW

**Comment by FelisCatus** [comment]
[proxy_switchyomega-2.5.0_0a14a871.zip](https://github.com/FelisCatus/SwitchyOmega/files/1202795/proxy_switchyomega-2.5.0_0a14a871.zip)

**Comment by daiheitan** [comment]
Seems not working

**Comment by FelisCatus** [comment]
Got it, I guess it wasn't a race condition. If only I can reproduce this...

Let me try it with a windows box later.

**Comment by FelisCatus** [comment]
See #1171 for detailed explanation regarding the issue. Further updates will be posted there.

Since this is a Firefox issue, this simply can't be fixed on SwitchyOmega's side. Therefore closing this PR as the changes are meaningless.

**Pull request closed without merging**
