### PR TITLE
add authentication on Socks5

### PR DESCRIPTION
**Pull request by ehsan21**
Hello,
there's Authentication option on Http and Https But is not on Socks5

please add Authentication on Socks5
add username + password for Setup (Socks5)

pr0

Thanks

### CODE REVIEW

**Comment by celeron533** [comment]
Is this a pull request? I couldn't see any commit made from your side. This is not the correct way to use the Pull Request.

As far as I know, Google Chrome does not support Socks5 Auth.
https://github.com/FelisCatus/SwitchyOmega/issues/178#issuecomment-134389642

I'm not clear whether Firefox implemented it or not.

**Comment by FelisCatus** [comment]
Chrome itself does not support SOCKS authentication. Even if we add a button there, it's not going to make authentication happen magically. Besides, this is not a valid pull request.

**Comment by olloff** [comment]
@FelisCatus Can it be implemented for Firefox? see [firefox-bug-1200802](https://bugzilla.mozilla.org/show_bug.cgi?id=1200802) -> [firefox-bug-1295807](https://bugzilla.mozilla.org/show_bug.cgi?id=1295807).
Currently its not possible to use credentials from password manager for socks auth, so it seems to be completely unusable on FF without extensions.

**Comment by FelisCatus** [comment]
Currently there isn't even any interface to supply proxy credentials for Web Extensions, so no. Let's wait until https://bugzilla.mozilla.org/show_bug.cgi?id=1381290 is done.

**Pull request closed without merging**
