### PR TITLE
Enlarge the extension icon

### PR DESCRIPTION
**Pull request by celeron533**
Now the icon size is as well as other extensions.

image

### CODE REVIEW

**Comment by celeron533** [comment]
There was a mistake in the commit, so I overwrite the commits.

**Comment by FelisCatus** [comment]
Wow, thanks for the PR. I will check it out soon.

Are these png files rendered from the svg file? And just out of curiosity, how did you change the canvas drawing code? Did you write the numbers by hand or generated it from the svg file?

**Comment by FelisCatus** [comment]
Looks good to me on Linux with both 1x and 2x. Need more testing on OS X though, because rendering tend to be special there. We want to ensure that the new icon doesn't look blurry.

**Comment by FelisCatus** [comment]
Taking a closer look, the 2x drawing is actually problematic:

2x_green_on_gray

The gray circle is actually surrounded by a thin ring of green, as shown clearly on the enlarged version:
2x_green_on_gray

More screenshots on this:

green_on_blue
green_on_gray
red_on_gray

**Comment by celeron533** [comment]
>Are these png files rendered from the svg file? And just out of curiosity, how did you change the canvas drawing code? Did you write the numbers by hand or generated it from the svg file?

1. I use Inkscape https://inkscape.org/ to process the original svg files: enlarge the circle size to a 'friendly' number.
2. However, the output file still have some rounding issues, such as 15.00001, 7.49992, so I manually tweak the raw svg file directly.
3. Finally, open the Inkscape again to generate png files.

**Comment by celeron533** [comment]
It looks like a feature... :)

>

**Comment by celeron533** [comment]
@FelisCatus , is it possible to change svg color on the fly then set it the into canvas directly?

**Comment by FelisCatus** [comment]
@celeron533 I'd say it is [definitely possible](http://stackoverflow.com/a/3769883) but requires manually modifying the svg source string and encoding it using base-64 into data-URI. I don't think that will make it easier than using canvas commands.

**Comment by marcosscriven** [comment]
I don't find the light-green on light-blue for the proxy mode high contrast enough. Could you consider making the difference between proxy and direct more clear please?

**Comment by FelisCatus** [comment]
@marcosscriven Please pick a custom color for your proxy profile. I mean, ANY color that has good contrast. This can be easily done by clicking the colored square on the top-left corner in the options page, when you select the proxy profile.

**Comment by FelisCatus** [comment]
This is pretty much dead for now... @celeron533, do you happen to have a version without the rounding? I think it could be something related to rounding with the curve parameters.

**Comment by celeron533** [comment]
Hi @FelisCatus , I have created a new pull request which does not round the icon curve parameters. Please review. 
:jack_o_lantern: Happy Halloween  :ghost:

**Pull request closed without merging**
