### PR TITLE
Support for changing the proxy profile from other chrome extensions

### PR DESCRIPTION
**Pull request by jodoglevy**
Related to #44

### CODE REVIEW

**Comment by jodoglevy** [comment]
@FelisCatus let me know you thoughts on this.

**Comment by FelisCatus** [comment]
Sorry, but... This PR effectively allows sending any command from any extension. By sending messages, any method on options can be called. Some are dangerous, while others are undocumented. It wouldn't be good if other extensions are starting to mess around by randomly calling public and private APIs, even if they do it for good purpose.

I think [external_api.coffee](https://github.com/FelisCatus/SwitchyOmega/blob/master/omega-target-chromium-extension/src/external_api.coffee) would be better for this. It also includes permission checks for known extensions just in case.

P.S. Implementing (or exposing) an API is trivial. However, we do have other stuff to consider. For example, how do users know that their profile are being changed by other extensions? If some extension keeps changing it to "DIRECT" every second, an average user could freak out.

Also, what's your use case for this? Are you developing an extension which needs to change the active profile? Why? Let's talk more about this on #44.

**Comment by jodoglevy** [comment]
What if I only specifically allow active profile change, and disallow changing to direct profile name? Then only way for another extension to change the profile would be if it already knew the profile names, and all it could possibly do is change the active profile. This works for my use cases.

Also, Chrome extensions can already do way worse things than change your proxy profile to direct. Including taking over the Chrome proxy all together, so it uses their extension instead of SwitchyOmega.

I'll just use my fork if need be, just trying to be helpful and contribute :)

**Comment by FelisCatus** [comment]
You can always use your own fork for your own use case. But just in case you are developing an published extension which interacts with SwitchyOmega, we can collaborate to make both of them works nicely together. That's the goal of the whole external API thing in SwitchyOmega.

> Also, Chrome extensions can already do way worse things than change your proxy profile to direct. Including taking over the Chrome proxy all together, so it uses their extension instead of SwitchyOmega.

In that case, SwitchyOmega displays a badge on the icon and also a popup menu explaining the situation that another extension is controlling the settings. The point is to let users know what happened, not maintaining the control.

Also, I was talking about activating the '[Direct Connection]' profile (which has a known name `direct`) in the other example. I apologize for using an inappropriate example though. However, I still think the user should be notified that some extension has activated the '[Direct Connection]' profile, instead of just let it happen magically.

**Comment by jodoglevy** [comment]
True on the proxy control point -- but I just meant that as an example. In general if users are installing extensions, those extensions can record their browsing behavior, redirect requests (even without the proxy permission -- ex with https://developer.chrome.com/extensions/webRequest), modify webpages without telling users, etc. What I meant was that there are many scenarios where the user may install a malicious chrome extension and they are not informed by anyone as to what it is doing. Even if it can't change the proxy profile, it can do a lot of other worse things.

Yes, I know you meant direction connection -- my use case does not need to ever set the proxy to use direct connection, that can be totally human initiated. So I am ok with modifying the pull request to only allow profile change and not allow change to the direct connection.profile, if that would be acceptable, since that wouldn't be much more work. But the extension I'm working on is for a client's business computers and will probably not be published to the store, so I don't really want to invest the time to look into the external_api.coffee way of doing this.

In any case, thanks for the willingness to chat about this.

**Comment by FelisCatus** [comment]
Sorry, but I think I've have to figure it out later. Meanwhile, you can just use your fork for your clients' private use for now. I will let you know when I start to work on the extension API.
Thanks again for providing the use case. Nice to talk with you.

**Pull request closed without merging**
